f_dep_dict = [
["D",["DEPT PHYS"]],
["M",["MESON SCI LAB"]],
["C",["INST COSM RAY RES", "INST COSMIC RAY RES", "COSM RAY RES INST"]],
["N",["INST NUCL STUDY", "INST NUCL PHYS", "INST NUCL STUD", "INST NUCL SCI", "CTR NUCL STUDY", "INST NUCL", "INST NUCL STUDIES", "INST PHYS NUCL", ]],
["S",["INST SOLID STATE PHYS", "DEPT SOLID STATE PHYS", "FAC SOLID STATE PHYS"]],
["L",["INST PHYS"]],
["P",["INT COLL ELEMENTARY PARTICLE PHYS LAB","INT COLL ELEMENTARY PARTICLE PHYS","INT COLL ELEMENTAR PARTICLE PHYS LAB","INT CTR ELEMENT PARTICLE PHYS","INT CTR ELEMENTARY PARTICLE PHYS","INT COLLABORAT ELEMENTARY PARTICLE PHYS LAB","LAB INT COLLABORAT ELEMENTARY PARTICLE PHYS", "INT COLLABORAT ELEMENTARY PARTICLE PHYS", "INT COLLABORAT ELEMENT PARTICLE PHYS", "INT COLLABORAT ELEMENT PARTICLE PHYS LAB","LAB INT COLL ELEMENTARY PARTICLE PHYS", "INT ELEMENTARY PARTICLE PHYS", "INT CTR PARTICLE PHYS"]]
]

fac_second_dep_list = ["DEPT PHYS", "MESON SCI LAB", "INT CTR ELEMENTARY PARTICLE PHYS", "INT COLLABORAT ELEMENTARY PARTICLE PHYS LAB"]
grad_second_dep_list = ["DEPT PHYS", "CTR NUCL STUDY"]
liveral_second_dep_list = ["DEPT PHYS", "INST PHYS"]
geneduc_second_dep_list = ["DEPT PHYS", "INST PHYS"]
schsci_second_dep_list = ['CTR NUCL STUDY']

