f_dep_dict = [
["D",["DEPT PHYS"]],
["M",["MESON SCI LAB"]],
["C",["INST COSM RAY RES", "INST COSMIC RAY RES"]],
["N",["INST NUCL STUDY", "INST NUCL PHYS", "INST NUCL STUD", "INST NUCL SCI"]],
["S",["INST SOLID STATE PHYS", "DEPT SOLID STATE PHYS", "FAC SOLID STATE PHYS"]],
["L",["INST PHYS"]],
["P",["INT COLL ELEMENTARY PARTICLE PHYS LAB","INT COLL ELEMENTARY PARTICLE PHYS","INT COLL ELEMENTAR PARTICLE PHYS LAB","INT CTR ELEMENT PARTICLE PHYS","INT CTR ELEMENTARY PARTICLE PHYS","INT COLLABORAT ELEMENTARY PARTICLE PHYS LAB","LAB INT COLLABORAT ELEMENTARY PARTICLE PHYS","LAB INT COLL ELEMENTARY PARTICLE PHYS"]]
]

fac_second_dep_list = ["DEPT PHYS", "MESON SCI LAB", "INT CTR ELEMENTARY PARTICLE PHYS", "INT COLLABORAT ELEMENTARY PARTICLE PHYS LAB"]
grad_second_dep_list = ["DEPT PHYS"]
liveral_second_dep_list = ["DEPT PHYS", "INST PHYS"]


