f_dep_dict = [
["D",["DEPT PHYS"]],
["M",["MESON SCI LAB"]],
["C",["INST COSM RAY RES", "INST COSM RAY RES ICRR", "INST COSMIC RAY RES"]],
["N",["CTR NUCL STUDY","INST NUCL","INST NUCL STUD","INST NUCL STUDY"]],
["S",["INST SOILD STATE PHYS","INST SOLID STATE PHYS","INST SOLID STATE PHYS ISSP","DEPT SOLID STATE PHYS","FAC SOLID STATE PHYS"]],
["L",["INST PHYS","COLL ARTS & SCI,DEPT PHYS", "COLL ARTS & SCI,INST PHYS", "COLL GEN EDUC,DEPT PHYS", "COLL GEN EDUC,INST PHYS"]],
["P",["INT COLL ELEMENTAR PARTICLE PHYS LAB","INT COLL ELEMENTARY PARTICLE PHYS","INT COLL ELEMENTARY PARTICLE PHYS LAB","INT COLLABORAT ELEMENT PARTICLE PHYS LAB","INT COLLABORAT ELEMENTARY PARTICLE PHYS","INT COLLABORAT ELEMENTARY PARTICLE PHYS LAB","INT CTR ELEMENT PARTICLE PHYS","INT CTR ELEMENTARY PARTICLE PHYS","LAB INT COLL ELEMENTARY PARTICLE PHYS"]]
]

fac_second_dep_list = ["DEPT PHYS", "MESON SCI LAB", "INT CTR ELEMENTARY PARTICLE PHYS", "INT COLLABORAT ELEMENTARY PARTICLE PHYS LAB"]
grad_second_dep_list = ["DEPT PHYS"]