black_list = ["INST SPACE & AERONAUT SCI",
              "INST SPACE & ASTRON SCI",
              "ADV SCI & TECHNOL RES CTR",
              "ADV SCI TECHNOL RES CTR",
              "CTR ISOTOPE",
              "CTR RADIOISOTOPE",
              "DEPT ASTRON",
              "DEPT BASIC SCI",
              "INST ASTRO",
              "INST ASTRON",
              #"INST PHYS",
              "INST PHYS & ASTRON",
              "INST PHYS & MATH",
              "INST PHYS & MATH UNIV",
              "INST PHYS & MATH UNIVERSE",
              "INST PHYS & MATH UNIVERSE IPMU",
              "NUCL SCI & TECHNOL RES CTR",
              "NUCL SCI & TECHNOL RES INST",
              "BIOSCI RES INST",
              "CTR COMP",
              "CTR CRYOGEN",
              "CTR CYTOGENET",
              "CTR ENVIRONM SCI",
              "DEPT ADV MAT",
              "DEPT ADV MAT SCI",
              "DEPT AGR CHEM",
              "DEPT APPL BIOL CHEM",
              "DEPT APPL CHEM",
              "DEPT APPL MATH",
              "DEPT APPL PHYS",
              "DEPT APPL SCI",
              "DEPT BIOCHEM & BIOTECHNOL",
              "DEPT BIOL",
              "DEPT BIOPHYS & LIFE SCI",
              "DEPT BIOTECHNOL",
              "DEPT BUNKYO KU",
              "DEPT CHEM",
              "DEPT CHEM ENGN",
              "DEPT COMP SCI",
              "DEPT EARTH & PLANETARY PHYS",
              "DEPT EARTH & PLANETARY SCI",
              "DEPT EARTH SCI & ASTRON",
              "DEPT ELECT & INFORMAT",
              "DEPT ELECT ENGN",
              "DEPT GEOPHYS",
              "DEPT IND & ENGN CHEM",
              "DEPT IND CHEM",
              "DEPT IND MANAGEMENT",
              "DEPT INFORMAT SCI",
              "DEPT INTERNAL MED 3",
              "DEPT LIFE SCI",
              "DEPT MAT ENGN",
              "DEPT MAT SCI & TECHNOL",
              "DEPT MATH",
              "DEPT MATH SCI",
              "DEPT MECH ENGN",
              "DEPT MED & PHYS THERAPY",
              "DEPT MED SCI",
              "DEPT PHARMACEUT SCI",
              "DEPT PHYSIOL CHEM & NUTR",
              "DEPT PURE & APPL SCI",
              "DEPT QUANTUM ENGN & SYST SCI",
              "DEPT SYNTHET CHEM",
              "DEPT VET PHYSIOL",
              "DIV LASER PHYS",
              "DIV MED",
              "EARTHQUAKE RES INST",
              "ENGN RES INST",
              "FAC AGR",
              "FAC CHEM",
              "FAC ENGN",
              "FAC IND SCI & TECHNOL",
              "FAC MED",
              "FAC PHARM SCI",
              "FAC PHARMACEUT SCI",
              "FAC SCI",
              "FAC SCI & TECHNOL",
              "FAC SURG",
              "FAC TECHNOL",
              "GRAD SCH ENGN",
              "GRAD SCH FRONTIER SCI",
              "GRAD SCH MED",
              "INST APPL MICROBIOL",
              "INST COLLOID & INTERFACE CHEM",
              "INST COLLOID & INTERFACE SCI",
              "INST ENGN INNOVAT",
              "INST ENGN RES",
              "INST GEN INFIRM",
              "INST GEOL",
              "INST GEOPHYS",
              "INST IND SCI",
              "INST MATH",
              "INST MED SCI",
              "INST MINERAL",
              "INST MOLEC & CELLULAR BIOSCI",
              "INST NANO QUANTUM INFORMAT ELECT",
              "INST NANO QUANTUM INFORMAT ELECTRON",
              "INST NUCL SAFETY",
              "OCEAN RES INST",
              "QPEC & DEPT APPL PHYS",
              "RES CTR ADV SCI & TECHNOL",
              "SCI & TECHNOL RES INST",
              "SCI RES INST",
              "TECHNOL RES INST"]
